<?php


class Dtn_Weblog_Block_Adminhtml_Blogpost_Edit_Form extends Mage_Adminhtml_Block_Widget_Form{
    protected function _prepareForm()
    {
        /**
         * Khởi tạo new một cái form bằng Varien_data_form
         */
        $form = new Varien_Data_Form([
            'id'=>'edit_form',
            'action'=>$this->getUrl('*/*/saveeeeee', array('id' => $this->getRequest()->getParam('id'))),
            'method'=> 'post'
        ]);
        $form->setUseContainer(true);
        $this->setForm($form);
        return parent::_prepareForm(); // TODO: Change the autogenerated stub
    }
    /**
 * nếu không dùng tab bên phía trái thì k cần tạo tabs và foderl tab và dùng luôn cái form này
 */
//    protected function _prepareForm()
//    {
//        $form = new Varien_Data_Form(array(//Nó giống như cái thẻ form trong html cũng có phương thức action
//            'id' => 'edit_form',
//            'action' => $this->getUrl('*/*/saveeeeee', array('id' => $this->getRequest()->getParam('id'))),
//            'method' => 'post',
//            'enctype' => 'multipart/form-data'
//        ));
//        $form->setUseContainer(true);
//        $this->setForm($form);
//        if (Mage::getSingleton('adminhtml/session')->getFormData()){
//            $data = Mage::getSingleton('adminhtml/session')->getFormData();
//            Mage::getSingleton('adminhtml/session')->setFormData(null);
//        }elseif(Mage::registry('blogpost_data'))
//            $data = Mage::registry('blogpost_data')->getData();
//        $fieldset = $form->addFieldset('blogpost_form', array('legend'=>Mage::helper('weblog')->__('Blogpost information')));
//        $fieldset->addField('title', 'text', array(
//            'label'     => Mage::helper('weblog')->__('Title'),
//            'class'     => 'required-entry',
//            'required'  => true,
//            'name'      => 'title',
//        ));
//        $fieldset->addField('post', 'text', array(
//            'label'     => Mage::helper('weblog')->__('Post'),
//            'class'     => 'required-entry',
//            'required'  => true,
//            'name'      => 'post',
//        ));
//        $form->setValues($data);
//        return parent::_prepareForm();
//
//    }
}