<?php
class Dtn_Weblog_Block_Adminhtml_Blogpost_Edit_Tabs extends Mage_Adminhtml_Block_Widget_Tabs

{
    protected function _construct()
    {
        parent::_construct(); // TODO: Change the autogenerated stub
        $this->setId('id');
        $this->setDestElementId('edit_form');
        $this->setTitle(Mage::helper('weblog')->__('Blogpost information'));//tiêu đề h1 tabs left
    }
}